version: '3.8'

services:
  # Android 14 ARM64 Container
  android-14-arm64:
    build:
      context: ./docker/android-14/arm64
      dockerfile: Dockerfile
    container_name: android-14-arm64-1
    privileged: true
    ports:
      - "5555:5555"  # ADB port
      - "8080:8080"  # Web interface (if available)
    environment:
      - ANDROID_VERSION=14
      - ARCH=arm64
      - GPS_LATITUDE=40.7128
      - GPS_LONGITUDE=-74.0060
      - GPS_ALTITUDE=10.0
      - GPS_ACCURACY=5.0
      - DEVICE_PROFILE=samsung_galaxy_s24
    volumes:
      - android_data_14_arm64:/data
      - ./modules/device-profiles:/system/etc/device-profiles:ro
      - ./modules/bypass-tools:/system/etc/bypass-tools:ro
      - ./modules/gps-injection:/system/etc/gps-injection:ro
      - /dev/kvm:/dev/kvm  # KVM acceleration if available
    tmpfs:
      - /tmp:exec,size=1g
    networks:
      - android-network
    healthcheck:
      test: ["/usr/local/bin/health-check.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    
  # Android 14 x86_64 Container
  android-14-x86_64:
    build:
      context: ./docker/android-14/x86_64
      dockerfile: Dockerfile
    container_name: android-14-x86_64-1
    privileged: true
    ports:
      - "5556:5555"  # ADB port
      - "8081:8080"  # Web interface
    environment:
      - ANDROID_VERSION=14
      - ARCH=x86_64
      - GPS_LATITUDE=34.0522
      - GPS_LONGITUDE=-118.2437
      - GPS_ALTITUDE=15.0
      - GPS_ACCURACY=3.0
      - DEVICE_PROFILE=google_pixel_8
    volumes:
      - android_data_14_x86_64:/data
      - ./modules/device-profiles:/system/etc/device-profiles:ro
      - ./modules/bypass-tools:/system/etc/bypass-tools:ro
      - ./modules/gps-injection:/system/etc/gps-injection:ro
      - /dev/kvm:/dev/kvm
    tmpfs:
      - /tmp:exec,size=1g
    networks:
      - android-network
    healthcheck:
      test: ["/usr/local/bin/health-check.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    
  # Android 13 ARM64 Container
  android-13-arm64:
    build:
      context: ./docker/android-13/arm64
      dockerfile: Dockerfile
    container_name: android-13-arm64-1
    privileged: true
    ports:
      - "5557:5555"  # ADB port
    environment:
      - ANDROID_VERSION=13
      - ARCH=arm64
      - GPS_LATITUDE=41.8781
      - GPS_LONGITUDE=-87.6298
      - GPS_ALTITUDE=5.0
      - DEVICE_PROFILE=samsung_galaxy_s23
    volumes:
      - android_data_13_arm64:/data
      - ./modules/device-profiles:/system/etc/device-profiles:ro
      - ./modules/bypass-tools:/system/etc/bypass-tools:ro
      - ./modules/gps-injection:/system/etc/gps-injection:ro
    tmpfs:
      - /tmp:exec,size=1g
    networks:
      - android-network
    healthcheck:
      test: ["/usr/local/bin/health-check.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    
  # Android 12 Container with Gaming Focus
  android-12-gaming:
    build:
      context: ./docker/android-12/arm64
      dockerfile: Dockerfile
    container_name: android-12-gaming-1
    privileged: true
    ports:
      - "5558:5555"  # ADB port
    environment:
      - ANDROID_VERSION=12
      - ARCH=arm64
      - GPS_LATITUDE=37.7749
      - GPS_LONGITUDE=-122.4194
      - GPS_ALTITUDE=20.0
      - DEVICE_PROFILE=oneplus_11
      - GAMING_MODE=true
    volumes:
      - android_data_12_gaming:/data
      - ./modules/device-profiles:/system/etc/device-profiles:ro
      - ./modules/bypass-tools:/system/etc/bypass-tools:ro
      - ./modules/gps-injection:/system/etc/gps-injection:ro
    tmpfs:
      - /tmp:exec,size=1g
    networks:
      - android-network
    healthcheck:
      test: ["/usr/local/bin/health-check.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

# Network configuration
networks:
  android-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

# Volume definitions
volumes:
  android_data_14_arm64:
    driver: local
  android_data_14_x86_64:
    driver: local
  android_data_13_arm64:
    driver: local
  android_data_12_gaming:
    driver: local