apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: android-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: android-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_DB
          value: android_platform
        - name: POSTGRES_USER
          value: acp_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: platform-secrets
              key: postgres-password
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        - name: init-db
          mountPath: /docker-entrypoint-initdb.d
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
      - name: init-db
        configMap:
          name: postgres-init

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: android-platform
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: android-platform
data:
  init.sql: |
    -- Initialize Android Container Platform Database
    CREATE INDEX IF NOT EXISTS idx_device_identities_instance_id ON device_identities(instance_id);
    CREATE INDEX IF NOT EXISTS idx_location_data_instance_id ON location_data(instance_id);
    CREATE INDEX IF NOT EXISTS idx_network_configs_instance_id ON network_configs(instance_id);
    CREATE INDEX IF NOT EXISTS idx_android_instances_status ON android_instances(status);
    CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);